/**
 * ADO InstaOto - Instagram-Automatisierung (Produkt: D:\repos\instagramoto).
 * Neue Texte fuer die Website (nicht aus einem anderen Projekt kopiert). DE + TR.
 */
export const instaTexts = {
  de: {
    nav: {
      start: 'Übersicht',
      flow: 'So funktioniert’s',
      features: 'Funktionen',
      process: 'Ablauf',
      security: 'Daten & Sicherheit',
      pricing: 'Preise & Anfrage',
    },
    group: { title: 'ADO InstaOto · Automation', short: 'Insta' },
    start: {
      eyebrow: 'Instagram-Automatisierung',
      line1: 'Jeder Kommentar',
      line2: 'bekommt eine Antwort.',
      lede: 'Schreibt jemand unter Ihren Beitrag, in eine Story-Antwort oder per DM ein Stichwort, antwortet Instagram sofort – rund um die Uhr. Was die Automatik nicht kann, übernimmt Ihr Team.',
      stats: [
        { v: '6 s', l: 'bis zur ersten Antwort' },
        { v: '24/7', l: 'automatisch erreichbar' },
        { v: '3–14', l: 'Tage bis live' },
        { v: '3', l: 'Kanäle: Kommentar, DM, Story' },
      ],
      video: 'Film ansehen',
      cta: 'So funktioniert’s',
    },
    flow: {
      eyebrow: 'Live ausprobieren',
      line1: 'Schreiben Sie',
      line2: '„Detail“.',
      stepsTitle: 'In 4 Schritten',
      hint: 'Tippen Sie ein Stichwort wie die Kundschaft – die Antwort kommt sofort.',
      placeholder: 'Kommentar schreiben …',
      send: 'Senden',
      user: 'lena.design',
      steps: ['Stichwort erkannt', 'Antwort mit Knöpfen', 'Follow-Prüfung', 'Link gesendet'],
      stepsHint: 'Schritt anklicken – das Telefon spielt ihn vor',
      bot: {
        hello: 'Hallo 👋 Möchtest du unsere Leistungen und Pakete sehen?',
        buttons: ['Ja, zeigen', 'Nein', 'Weiss nicht'],
        follow: 'Folgst du uns schon? Dann schicke ich dir gleich den Link.',
        followBtn: 'Ich folge',
        link: 'Hier ist alles im Überblick:',
        no: 'Kein Problem – schreib einfach „Detail“, wenn du es dir anders überlegst.',
        human: 'Ich gebe dich an unser Team weiter. Wir melden uns persönlich.',
        unknown: 'Unbekanntes Stichwort. Versuchen Sie „Detail“, „Preis“ oder „Link“.',
      },
      keywords: ['Detail', 'Preis', 'Link'],
    },
    features: {
      eyebrow: 'Das Panel',
      tab: 'Funktionen',
      line1: 'Alles in',
      line2: 'einer Oberfläche.',
      items: [
        { t: 'Abläufe', d: 'Stichwörter, Kanäle und Beiträge festlegen – ein- und ausschalten mit einem Klick.' },
        { t: 'Editor', d: 'Schritte mit Knöpfen, Verzweigungen, Follow-Prüfung und Link. Instagram-Regeln werden live geprüft.' },
        { t: 'Simulator', d: 'Jeden Ablauf vorab am Telefon-Vorschau testen – mit der echten Logik.' },
        { t: 'Posteingang', d: 'Alle Gespräche pro Person; übergebene Anfragen beantwortet Ihr Team direkt.' },
        { t: 'Beiträge', d: 'Ihre Posts, Reels und Stories – einen Ablauf direkt an einen Beitrag hängen.' },
        { t: 'Auswertung', d: 'Gestartet, Link geöffnet, abgeschlossen – pro Tag und pro Ablauf.' },
      ],
    },
    process: {
      eyebrow: 'Ablauf',
      tab: 'Von der Anfrage bis live',
      line1: 'Von der Anfrage',
      line2: 'bis live.',
      steps: [
        { t: 'Gespräch', d: 'Wir klären Ziel, Stichwörter und welche Beiträge automatisch antworten sollen.', time: 'Tag 1' },
        { t: 'Zugänge', d: 'Sie verbinden Ihr Instagram-Konto selbst über „Mit Instagram verbinden“ – wir sehen kein Passwort.', time: 'Tag 1' },
        { t: 'Inhalte', d: 'Sie liefern die Texte und Links für die Antworten.', time: 'Tag 2' },
        { t: 'Einrichtung', d: 'Wir bauen die Abläufe, testen sie im Simulator und mit einem Testkonto.', time: 'Tag 2–3' },
        { t: 'Live', d: 'Freischalten, gemeinsam prüfen, Ihr Team bekommt den Zugang zum Panel.', time: 'Tag 3' },
      ],
    },
    security: {
      eyebrow: 'Daten & Sicherheit',
      line1: 'Ihre Daten',
      line2: 'bleiben in Europa.',
      items: [
        { t: 'Datenbank in Frankfurt', d: 'Abläufe, Gespräche und Auswertungen liegen in einer eigenen Datenbank in der EU.' },
        { t: 'Zugänge verschlüsselt', d: 'Instagram-Schlüssel werden mit AES-256 verschlüsselt und sind für den Browser nie lesbar.' },
        { t: 'Signierte Nachrichten', d: 'Jede Meldung von Instagram wird über ihre Signatur geprüft, bevor sie verarbeitet wird.' },
        { t: 'Automatische Verlängerung', d: 'Der Instagram-Zugang wird täglich geprüft und rechtzeitig erneuert.' },
        { t: 'Datenlöschung', d: 'Personen können ihre Daten jederzeit löschen lassen – die Seite dafür ist eingerichtet.' },
        { t: 'Anmeldung ohne Passwort', d: 'Ihr Team meldet sich mit einem Einmal-Code per E-Mail an.' },
      ],
      hint: 'Zeiger auf einen Kreis – kurz erklärt.',
    },
    pricing: {
      eyebrow: 'Preise & Anfrage',
      line1: 'Klare',
      line2: 'Preise.',
      lede: 'Einmal einrichten, dann läuft es. Sie wählen, wie viel wir für Sie übernehmen – vom fertigen Konto bis zu allem bei Meta.',
      hostingNote: 'Datenbank & Hosting: in den meisten Fällen kostenlos.',
      currency: 'CHF',
      setupLabel: 'Einrichtung · einmalig',
      careLabel: 'Betreuung · freiwillig',
      perMonth: 'Monat',
      once: 'einmalig',
      choose: 'Dieses Paket anfragen',
      back: 'Zurück zum Paket',
      recommended: 'Empfohlen',
      hourly: 'Ohne Betreuung: Einzelaufträge CHF 90.– / Stunde',
      plans: [
        {
          id: 'start',
          name: 'Start',
          price: '290',
          care: false,
          goal: 'Instagram beantwortet Nachrichten und Kommentare automatisch. Ihre Konten bei Meta sind schon eingerichtet.',
          time: 'ca. 3 Arbeitstage + Prüfung durch Meta',
          you: [
            'Instagram-Profikonto (Business oder Creator)',
            'Facebook-Seite, mit Instagram verknüpft',
            'Meta Business-Portfolio, Sie als Admin',
            'Zwei-Faktor-Anmeldung aktiv',
            'Firma bei Meta verifiziert',
            'Stichwörter, Antworten, Links',
            'E-Mail-Adressen Ihres Teams',
          ],
          we: [
            'Meta-App mit Rechten für Nachrichten und Kommentare',
            'App-Prüfung bei Meta',
            'Webhook, Panel und Datenbank in der EU',
            'E-Mail-Absender für die Anmeldung',
            'Ihre Abläufe einrichten und testen',
            'Einweisung für Ihr Team',
          ],
        },
        {
          id: 'komplett',
          name: 'Komplett',
          price: '490',
          care: false,
          goal: 'Dasselbe Ergebnis – Sie kümmern sich um nichts, auch nicht um die Konten bei Meta.',
          time: 'ca. 1–2 Wochen – die Verifizierung bei Meta braucht Zeit',
          you: [
            'Anmeldung bei Instagram (Sie melden sich selbst an)',
            'Handelsregisterauszug oder UID',
            'Stichwörter und Antworten – oder wir schreiben sie mit Ihnen',
            'E-Mail-Adressen Ihres Teams',
          ],
          we: [
            'Alles aus Start',
            'Instagram auf Profikonto umstellen',
            'Facebook-Seite und Business-Portfolio anlegen',
            'Zwei-Faktor-Anmeldung mit Ihnen einrichten',
            'Ihre Firma bei Meta verifizieren',
            'Erste Texte mit Ihnen schreiben',
          ],
        },
        {
          id: 'basis',
          name: 'Basis',
          price: '39',
          care: true,
          goal: 'Es läuft weiter, auch wenn Meta etwas ändert – und Sie haben einen festen Ansprechpartner.',
          time: 'monatlich',
          you: ['InstaOto ist eingerichtet (Start oder Komplett)', 'Fragen und Wünsche per E-Mail'],
          we: ['Antwort innert 48 Stunden', 'Eine kleine Änderung pro Monat', 'Anpassung, wenn Meta etwas ändert', 'Zugang und Webhook im Blick'],
        },
        {
          id: 'plus',
          name: 'Plus',
          price: '79',
          care: true,
          goal: 'Ihr Instagram wächst – neue Aktionen und Abläufe ohne Wartezeit.',
          time: 'monatlich',
          you: ['InstaOto ist eingerichtet (Start oder Komplett)', 'Ideen für neue Aktionen'],
          we: ['Alles aus Basis', 'Kleine Änderungen ohne Limit', 'Neue Abläufe, z. B. für Aktionen', 'Antwort innert 24 Stunden'],
        },
      ],
      goalLabel: 'Ziel',
      youLabel: 'Das bringen Sie mit',
      weLabel: 'Das erledigen wir',
      timeLabel: 'Dauer',
      form: {
        namePlaceholder: 'Ihr Name',
        emailPlaceholder: 'Ihre E-Mail-Adresse',
        messagePlaceholder: 'Ihr Instagram-Konto und wofür Sie es nutzen …',
        successTitle: 'Mailprogramm geöffnet',
        successText: 'Ihre Anfrage ist vorbereitet – bitte im Mailprogramm noch abschicken.',
        mailSubjectPrefix: 'InstaOto-Anfrage von',
      },
    },
  },
  tr: {
    nav: {
      start: 'Genel Bakış',
      flow: 'Nasıl çalışır',
      features: 'Özellikler',
      process: 'Süreç',
      security: 'Veri & Güvenlik',
      pricing: 'Fiyat & Talep',
    },
    group: { title: 'ADO InstaOto · Otomasyon', short: 'Insta' },
    start: {
      eyebrow: 'Instagram otomasyonu',
      line1: 'Her yorum',
      line2: 'bir cevap alır.',
      lede: 'Biri gönderinizin altına, story cevabına ya da DM’e bir kelime yazınca Instagram hemen cevap verir – 7/24. Otomatiğin yapamadığını ekibiniz devralır.',
      stats: [
        { v: '6 sn', l: 'ilk cevaba kadar' },
        { v: '7/24', l: 'otomatik ulaşılabilir' },
        { v: '3–14', l: 'günde yayında' },
        { v: '3', l: 'kanal: yorum, DM, story' },
      ],
      video: 'Filmi izle',
      cta: 'Nasıl çalışır',
    },
    flow: {
      eyebrow: 'Canlı deneyin',
      line1: 'Yazın:',
      line2: '„Detay“.',
      stepsTitle: '4 adımda',
      hint: 'Müşteri gibi bir kelime yazın – cevap hemen gelir.',
      placeholder: 'Yorum yaz …',
      send: 'Gönder',
      user: 'lena.design',
      steps: ['Kelime tanındı', 'Düğmeli cevap', 'Takip kontrolü', 'Link gönderildi'],
      stepsHint: 'Bir adıma tıklayın – telefon onu oynatır',
      bot: {
        hello: 'Merhaba 👋 Hizmetlerimizi ve paketlerimizi görmek ister misin?',
        buttons: ['Evet, göster', 'Hayır', 'Bilmiyorum'],
        follow: 'Bizi takip ediyor musun? O zaman linki hemen gönderiyorum.',
        followBtn: 'Takip ediyorum',
        link: 'Hepsi burada:',
        no: 'Sorun değil – fikrin değişirse „Detay“ yazman yeterli.',
        human: 'Seni ekibimize aktarıyorum. Kişisel olarak dönüş yapacağız.',
        unknown: 'Bilinmeyen kelime. „Detay“, „Fiyat“ ya da „Link“ deneyin.',
      },
      keywords: ['Detay', 'Fiyat', 'Link'],
    },
    features: {
      eyebrow: 'Panel',
      tab: 'Özellikler',
      line1: 'Her şey',
      line2: 'tek ekranda.',
      items: [
        { t: 'Akışlar', d: 'Kelimeleri, kanalları ve gönderileri belirleyin – tek tıkla açıp kapatın.' },
        { t: 'Düzenleyici', d: 'Düğmeli adımlar, dallanma, takip kontrolü ve link. Instagram kuralları anında kontrol edilir.' },
        { t: 'Simülatör', d: 'Her akışı önceden telefon önizlemesinde gerçek motorla deneyin.' },
        { t: 'Gelen kutusu', d: 'Kişi bazında tüm sohbetler; devredilen talepleri ekibiniz doğrudan cevaplar.' },
        { t: 'Paylaşımlar', d: 'Gönderi, Reels ve story’leriniz – akışı doğrudan bir paylaşıma bağlayın.' },
        { t: 'Raporlar', d: 'Başlayan, link açılan, tamamlanan – gün ve akış bazında.' },
      ],
    },
    process: {
      eyebrow: 'Süreç',
      tab: 'Talepten yayına',
      line1: 'Talepten',
      line2: 'yayına.',
      steps: [
        { t: 'Görüşme', d: 'Hedefi, kelimeleri ve hangi paylaşımların otomatik cevap vereceğini konuşuruz.', time: '1. gün' },
        { t: 'Erişim', d: 'Instagram hesabınızı „Instagram ile bağlan“ ile kendiniz bağlarsınız – şifrenizi görmeyiz.', time: '1. gün' },
        { t: 'İçerik', d: 'Cevaplar için metinleri ve linkleri siz verirsiniz.', time: '2. gün' },
        { t: 'Kurulum', d: 'Akışları kurar, simülatörde ve test hesabıyla deneriz.', time: '2.–3. gün' },
        { t: 'Yayın', d: 'Açarız, birlikte kontrol ederiz, ekibiniz panele erişim alır.', time: '3. gün' },
      ],
    },
    security: {
      eyebrow: 'Veri & Güvenlik',
      line1: 'Verileriniz',
      line2: 'Avrupa’da kalır.',
      items: [
        { t: 'Veritabanı Frankfurt’ta', d: 'Akışlar, sohbetler ve raporlar AB’deki kendi veritabanında durur.' },
        { t: 'Erişimler şifreli', d: 'Instagram anahtarları AES-256 ile şifrelenir, tarayıcı asla okuyamaz.' },
        { t: 'İmzalı mesajlar', d: 'Instagram’dan gelen her bildirim işlenmeden önce imzasıyla kontrol edilir.' },
        { t: 'Otomatik yenileme', d: 'Instagram erişimi her gün kontrol edilir ve zamanında yenilenir.' },
        { t: 'Veri silme', d: 'Kişiler verilerini istedikleri an sildirebilir – sayfası hazır.' },
        { t: 'Şifresiz giriş', d: 'Ekibiniz e-postayla gelen tek kullanımlık kodla girer.' },
      ],
      hint: 'Bir dairenin üstüne gelin – kısaca açıklanır.',
    },
    pricing: {
      eyebrow: 'Fiyat & Talep',
      line1: 'Net',
      line2: 'fiyatlar.',
      lede: 'Bir kez kurulur, sonra kendi çalışır. Ne kadarını bize bırakacağınızı siz seçersiniz – hazır hesaptan Meta’daki her işe kadar.',
      hostingNote: 'Veritabanı ve barındırma: çoğu durumda ücretsiz.',
      currency: 'CHF',
      setupLabel: 'Kurulum · tek sefer',
      careLabel: 'Destek · isteğe bağlı',
      perMonth: 'ay',
      once: 'tek sefer',
      choose: 'Bu paketi iste',
      back: 'Pakete dön',
      recommended: 'Önerilen',
      hourly: 'Destek almadan: tek tek işler CHF 90.– / saat',
      plans: [
        {
          id: 'start',
          name: 'Start',
          price: '290',
          care: false,
          goal: 'Instagram mesajlara ve yorumlara otomatik cevap verir. Meta’daki hesaplarınız zaten hazır.',
          time: 'yaklaşık 3 iş günü + Meta incelemesi',
          you: [
            'Instagram profesyonel hesap (İşletme ya da İçerik Üretici)',
            'Instagram’a bağlı Facebook sayfası',
            'Meta Business Portfolio, siz yönetici',
            'İki adımlı giriş açık',
            'Firmanız Meta’da doğrulanmış',
            'Kelimeler, cevaplar, linkler',
            'Ekibinizin e-posta adresleri',
          ],
          we: [
            'Mesaj ve yorum izinli Meta uygulaması',
            'Meta’nın uygulama incelemesi',
            'Webhook, panel ve AB’de veritabanı',
            'Giriş için e-posta göndericisi',
            'Akışlarınızı kurmak ve test etmek',
            'Ekibinize tanıtım',
          ],
        },
        {
          id: 'komplett',
          name: 'Komplett',
          price: '490',
          care: false,
          goal: 'Aynı sonuç – hiçbir şeyle uğraşmazsınız, Meta’daki hesaplar dahil.',
          time: 'yaklaşık 1–2 hafta – Meta doğrulaması zaman alır',
          you: [
            'Instagram girişi (girişi siz yaparsınız)',
            'Ticaret sicili çıktısı ya da UID',
            'Kelimeler ve cevaplar – ya da sizinle birlikte yazarız',
            'Ekibinizin e-posta adresleri',
          ],
          we: [
            'Start’taki her şey',
            'Instagram’ı profesyonel hesaba çevirmek',
            'Facebook sayfası ve Business Portfolio kurmak',
            'İki adımlı girişi sizinle açmak',
            'Firmanızı Meta’da doğrulatmak',
            'İlk metinleri sizinle yazmak',
          ],
        },
        {
          id: 'basis',
          name: 'Basis',
          price: '39',
          care: true,
          goal: 'Meta bir şey değiştirse de sistem çalışmaya devam eder – ve sabit bir muhatabınız olur.',
          time: 'aylık',
          you: ['InstaOto kurulu (Start ya da Komplett)', 'Soru ve istekler e-postayla'],
          we: ['48 saat içinde cevap', 'Ayda bir küçük değişiklik', 'Meta değişikliklerine uyum', 'Erişim ve webhook takibi'],
        },
        {
          id: 'plus',
          name: 'Plus',
          price: '79',
          care: true,
          goal: 'Instagram’ınız büyüyor – yeni kampanyalar ve akışlar beklemeden.',
          time: 'aylık',
          you: ['InstaOto kurulu (Start ya da Komplett)', 'Yeni kampanya fikirleri'],
          we: ['Basis’teki her şey', 'Sınırsız küçük değişiklik', 'Yeni akışlar, örn. kampanyalar için', '24 saat içinde cevap'],
        },
      ],
      goalLabel: 'Amaç',
      youLabel: 'Sizden gerekenler',
      weLabel: 'Bizim yaptıklarımız',
      timeLabel: 'Süre',
      form: {
        namePlaceholder: 'Adınız',
        emailPlaceholder: 'E-posta adresiniz',
        messagePlaceholder: 'Instagram hesabınız ve ne için kullandığınız …',
        successTitle: 'E-posta programı açıldı',
        successText: 'Talebiniz hazır – lütfen e-posta programında gönderin.',
        mailSubjectPrefix: 'InstaOto talebi:',
      },
    },
  },
};

export type InstaTexts = (typeof instaTexts)['de'];
