/**
 * ADO InstaOto - Instagram-Automatisierung (Produkt: D:\repos\instagramoto).
 * Neue Texte fuer die Website (nicht aus einem anderen Projekt kopiert). DE + TR.
 */
export const instaTexts = {
  de: {
    nav: {
      start: 'Übersicht',
      flow: 'So funktioniert’s',
      features: 'Funktionen',
      process: 'Ablauf',
      security: 'Daten & Sicherheit',
      pricing: 'Preise & Anfrage',
    },
    group: { title: 'ADO InstaOto · Automation', short: 'Insta' },
    start: {
      eyebrow: 'Instagram-Automatisierung',
      line1: 'Jeder Kommentar',
      line2: 'bekommt eine Antwort.',
      lede: 'Schreibt jemand unter Ihren Beitrag, in eine Story-Antwort oder per DM ein Stichwort, startet automatisch ein Gespräch: mit Knöpfen, Follow-Prüfung, Link und Übergabe an Ihr Team – rund um die Uhr, ohne Monatsabo.',
      stats: [
        { v: '6 s', l: 'bis zur ersten Antwort' },
        { v: '24/7', l: 'automatisch erreichbar' },
        { v: '0', l: 'Monatsabo' },
        { v: '3', l: 'Kanäle: Kommentar, DM, Story' },
      ],
      video: 'Film ansehen',
      cta: 'So funktioniert’s',
    },
    flow: {
      eyebrow: 'Live ausprobieren',
      line1: 'Schreiben Sie',
      line2: '„Detail“.',
      hint: 'Tippen Sie ein Stichwort wie die Kundschaft – die Antwort kommt sofort.',
      placeholder: 'Kommentar schreiben …',
      send: 'Senden',
      user: 'lena.design',
      steps: ['Stichwort erkannt', 'Antwort mit Knöpfen', 'Follow-Prüfung', 'Link gesendet'],
      stepsHint: 'Schritt anklicken – das Telefon spielt ihn vor',
      bot: {
        hello: 'Hallo 👋 Möchtest du unsere Leistungen und Pakete sehen?',
        buttons: ['Ja, zeigen', 'Nein', 'Weiss nicht'],
        follow: 'Folgst du uns schon? Dann schicke ich dir gleich den Link.',
        followBtn: 'Ich folge',
        link: 'Hier ist alles im Überblick:',
        no: 'Kein Problem – schreib einfach „Detail“, wenn du es dir anders überlegst.',
        human: 'Ich gebe dich an unser Team weiter. Wir melden uns persönlich.',
        unknown: 'Unbekanntes Stichwort. Versuchen Sie „Detail“, „Preis“ oder „Link“.',
      },
      keywords: ['Detail', 'Preis', 'Link'],
    },
    features: {
      eyebrow: 'Das Panel',
      line1: 'Alles in',
      line2: 'einer Oberfläche.',
      items: [
        { t: 'Abläufe', d: 'Stichwörter, Kanäle und Beiträge festlegen – ein- und ausschalten mit einem Klick.' },
        { t: 'Editor', d: 'Schritte mit Knöpfen, Verzweigungen, Follow-Prüfung und Link. Instagram-Regeln werden live geprüft.' },
        { t: 'Simulator', d: 'Jeden Ablauf vorab am Telefon-Vorschau testen – mit der echten Logik.' },
        { t: 'Posteingang', d: 'Alle Gespräche pro Person; übergebene Anfragen beantwortet Ihr Team direkt.' },
        { t: 'Beiträge', d: 'Ihre Posts, Reels und Stories – einen Ablauf direkt an einen Beitrag hängen.' },
        { t: 'Auswertung', d: 'Gestartet, Link geöffnet, abgeschlossen – pro Tag und pro Ablauf.' },
      ],
    },
    process: {
      eyebrow: 'Ablauf',
      line1: 'Von der Anfrage',
      line2: 'bis live.',
      steps: [
        { t: 'Gespräch', d: 'Wir klären Ziel, Stichwörter und welche Beiträge automatisch antworten sollen.', time: 'Tag 1' },
        { t: 'Zugänge', d: 'Sie verbinden Ihr Instagram-Konto selbst über „Mit Instagram verbinden“ – wir sehen kein Passwort.', time: 'Tag 1' },
        { t: 'Inhalte', d: 'Sie liefern Texte, Links und Knöpfe – oder wir schreiben sie mit Ihnen.', time: 'Tag 2' },
        { t: 'Einrichtung', d: 'Wir bauen die Abläufe, testen sie im Simulator und mit einem Testkonto.', time: 'Tag 2–3' },
        { t: 'Live', d: 'Freischalten, gemeinsam prüfen, Ihr Team bekommt den Zugang zum Panel.', time: 'Tag 3' },
      ],
      needTitle: 'Was wir von Ihnen brauchen',
      need: [
        { t: 'Instagram Business- oder Creator-Konto', d: 'Kostenlos in den Instagram-Einstellungen umstellbar.' },
        { t: 'Facebook-Seite und Meta Business-Portfolio', d: 'Mit dem Instagram-Konto verknüpft, Zwei-Faktor-Anmeldung aktiv. Im Paket Komplett richten wir das mit Ihnen ein.' },
        { t: 'Ein Klick „Mit Instagram verbinden“', d: 'Offizielle Meta-Anmeldung. Der Zugang wird verschlüsselt gespeichert.' },
        { t: 'Stichwörter & Texte', d: 'Welche Wörter lösen was aus? Welche Antwort, welcher Link?' },
        { t: 'E-Mail-Adressen Ihres Teams', d: 'Anmeldung am Panel per Code – ohne Passwort.' },
      ],
      sendTitle: 'So schicken Sie uns alles',
      send: 'Texte und Links per E-Mail oder als Notiz im Anfrageformular. Zugänge und Passwörter schicken Sie nie per E-Mail – die Verbindung machen Sie selbst mit einem Klick.',
    },
    security: {
      eyebrow: 'Daten & Sicherheit',
      line1: 'Ihre Daten',
      line2: 'bleiben in Europa.',
      items: [
        { t: 'Datenbank in Frankfurt', d: 'Abläufe, Gespräche und Auswertungen liegen in einer eigenen Datenbank in der EU.' },
        { t: 'Zugänge verschlüsselt', d: 'Instagram-Schlüssel werden mit AES-256 verschlüsselt und sind für den Browser nie lesbar.' },
        { t: 'Signierte Nachrichten', d: 'Jede Meldung von Instagram wird über ihre Signatur geprüft, bevor sie verarbeitet wird.' },
        { t: 'Automatische Verlängerung', d: 'Der Instagram-Zugang wird täglich geprüft und rechtzeitig erneuert.' },
        { t: 'Datenlöschung', d: 'Personen können ihre Daten jederzeit löschen lassen – die Seite dafür ist eingerichtet.' },
        { t: 'Anmeldung ohne Passwort', d: 'Ihr Team meldet sich mit einem Einmal-Code per E-Mail an.' },
      ],
      dbTitle: 'Braucht es eine eigene Datenbank?',
      dbText: 'Ja – sie wird bei der Einrichtung für Sie angelegt. Für die meisten Betriebe reicht die kostenlose Stufe; bei sehr vielen Gesprächen sprechen wir über die nächste Stufe.',
    },
    pricing: {
      eyebrow: 'Preise & Anfrage',
      line1: 'Klare',
      line2: 'Preise.',
      lede: 'Einmal einrichten, dann läuft es. Sie wählen, wie viel wir für Sie übernehmen – vom fertigen Konto bis zu allem bei Meta.',
      included: ['Einrichtung und erste Abläufe', 'Panel-Zugang für Ihr Team', 'Datenbank in der EU', 'Einweisung und Test', 'Kein Monatsabo'],
      /** Preisrahmen ohne Zahl. */
      terms: [
        { t: 'Einmalig', d: 'Einmal eingerichtet – danach läuft es von selbst.' },
        { t: 'Software ohne Monatsabo', d: 'Keine Lizenzkosten – Betreuung nur, wenn Sie sie möchten.' },
        { t: 'Fester Preis', d: 'Sie sehen den Preis vorher. Keine Überraschungen.' },
        { t: 'Einweisung inklusive', d: 'Wir zeigen Ihrem Team alles einmal in Ruhe. Laufende Betreuung ist auf Wunsch möglich – gegen Aufpreis.' },
      ],
      includedLabel: 'Inbegriffen',
      hostingNote: 'Datenbank & Hosting: in den meisten Fällen kostenlos.',
      currency: 'CHF',
      packsTitle: 'Pakete',
      choose: 'Dieses Paket anfragen',
      recommended: 'Empfohlen',
      packs: [
        {
          name: 'Start',
          price: '290',
          unit: 'einmalig',
          for: 'Ihr Instagram-Profikonto, die Facebook-Seite und das Meta Business-Portfolio sind schon bereit.',
          incl: ['Meta-App und Webhook', 'Panel und Datenbank in der EU', 'Ihre Abläufe', 'Einweisung und Test'],
        },
        {
          name: 'Komplett',
          price: '490',
          unit: 'einmalig',
          for: 'Sie möchten sich um nichts kümmern – wir erledigen auch alles bei Meta.',
          incl: ['Alles aus Start', 'Verifizierung bei Meta', 'App-Prüfung bei Meta', 'E-Mail-Absender für die Anmeldung'],
        },
      ],
      careTitle: 'Betreuung – freiwillig',
      care: [
        { name: 'Basis', price: '39', unit: 'pro Monat', d: 'Fragen per E-Mail (Antwort in 48 h), eine kleine Änderung im Monat, Anpassung bei Änderungen von Meta.' },
        { name: 'Plus', price: '79', unit: 'pro Monat', d: 'Kleine Änderungen ohne Limit, neue Abläufe, Vorrang.' },
      ],
      hourly: 'Ohne Betreuung: einzelne Aufträge CHF 90.– pro Stunde.',
      checkTitle: 'Das braucht es',
      checkHint: 'Haken Sie an, was schon bereit ist – wir sagen Ihnen, welches Paket passt.',
      readyAll: 'Alles bereit – das Paket Start reicht.',
      readySome: 'Noch nicht alles bereit – Komplett nimmt Ihnen das ab.',
      checkGroups: [
        {
          t: 'Ihre Konten',
          own: true,
          items: [
            { t: 'Instagram-Profikonto', d: 'Business oder Creator – in den Instagram-Einstellungen umstellbar.' },
            { t: 'Facebook-Seite', d: 'Mit dem Instagram-Konto verknüpft.' },
            { t: 'Zwei-Faktor-Anmeldung', d: 'Auf Ihrem Facebook-Konto aktiv – Meta verlangt das.' },
            { t: 'Meta Business-Portfolio', d: 'Seite und Instagram-Konto darin, Sie als Admin.' },
            { t: 'Firmennachweis', d: 'Handelsregisterauszug oder UID, Adresse, Telefon – für die Verifizierung bei Meta.' },
          ],
        },
        {
          t: 'Technik – im Paket Komplett von uns',
          own: false,
          items: [
            { t: 'Meta-Entwicklerkonto und App', d: '' },
            { t: 'Rechte für Nachrichten und Kommentare', d: '' },
            { t: 'App-Prüfung bei Meta', d: 'Datenschutz- und Löschseite, Bildschirmvideo – dauert Tage bis Wochen.' },
            { t: 'Webhook, Datenbank in der EU, Hosting', d: '' },
            { t: 'E-Mail-Absender für die Anmeldecodes', d: '' },
            { t: 'Automatische Erneuerung des Zugangs', d: '' },
          ],
        },
        {
          t: 'Ihre Inhalte',
          own: false,
          items: [
            { t: 'Stichwörter, Antworten, Links', d: 'Welches Wort löst was aus?' },
            { t: 'E-Mail-Adressen Ihres Teams', d: 'Für die Anmeldung am Panel.' },
          ],
        },
      ],
      form: {
        namePlaceholder: 'Ihr Name',
        emailPlaceholder: 'Ihre E-Mail-Adresse',
        messagePlaceholder: 'Ihr Instagram-Konto und wofür Sie es nutzen …',
        successTitle: 'Mailprogramm geöffnet',
        successText: 'Ihre Anfrage ist vorbereitet – bitte im Mailprogramm noch abschicken.',
        mailSubjectPrefix: 'InstaOto-Anfrage von',
      },
    },
  },
  tr: {
    nav: {
      start: 'Genel Bakış',
      flow: 'Nasıl çalışır',
      features: 'Özellikler',
      process: 'Süreç',
      security: 'Veri & Güvenlik',
      pricing: 'Fiyat & Talep',
    },
    group: { title: 'ADO InstaOto · Otomasyon', short: 'Insta' },
    start: {
      eyebrow: 'Instagram otomasyonu',
      line1: 'Her yorum',
      line2: 'bir cevap alır.',
      lede: 'Biri gönderinizin altına, story cevabına ya da DM’e bir kelime yazınca otomatik bir sohbet başlar: düğmeler, takip kontrolü, link ve ekibinize devretme – 7/24, aylık abonelik olmadan.',
      stats: [
        { v: '6 sn', l: 'ilk cevaba kadar' },
        { v: '7/24', l: 'otomatik ulaşılabilir' },
        { v: '0', l: 'aylık abonelik' },
        { v: '3', l: 'kanal: yorum, DM, story' },
      ],
      video: 'Filmi izle',
      cta: 'Nasıl çalışır',
    },
    flow: {
      eyebrow: 'Canlı deneyin',
      line1: 'Yazın:',
      line2: '„Detay“.',
      hint: 'Müşteri gibi bir kelime yazın – cevap hemen gelir.',
      placeholder: 'Yorum yaz …',
      send: 'Gönder',
      user: 'lena.design',
      steps: ['Kelime tanındı', 'Düğmeli cevap', 'Takip kontrolü', 'Link gönderildi'],
      stepsHint: 'Bir adıma tıklayın – telefon onu oynatır',
      bot: {
        hello: 'Merhaba 👋 Hizmetlerimizi ve paketlerimizi görmek ister misin?',
        buttons: ['Evet, göster', 'Hayır', 'Bilmiyorum'],
        follow: 'Bizi takip ediyor musun? O zaman linki hemen gönderiyorum.',
        followBtn: 'Takip ediyorum',
        link: 'Hepsi burada:',
        no: 'Sorun değil – fikrin değişirse „Detay“ yazman yeterli.',
        human: 'Seni ekibimize aktarıyorum. Kişisel olarak dönüş yapacağız.',
        unknown: 'Bilinmeyen kelime. „Detay“, „Fiyat“ ya da „Link“ deneyin.',
      },
      keywords: ['Detay', 'Fiyat', 'Link'],
    },
    features: {
      eyebrow: 'Panel',
      line1: 'Her şey',
      line2: 'tek ekranda.',
      items: [
        { t: 'Akışlar', d: 'Kelimeleri, kanalları ve gönderileri belirleyin – tek tıkla açıp kapatın.' },
        { t: 'Düzenleyici', d: 'Düğmeli adımlar, dallanma, takip kontrolü ve link. Instagram kuralları anında kontrol edilir.' },
        { t: 'Simülatör', d: 'Her akışı önceden telefon önizlemesinde gerçek motorla deneyin.' },
        { t: 'Gelen kutusu', d: 'Kişi bazında tüm sohbetler; devredilen talepleri ekibiniz doğrudan cevaplar.' },
        { t: 'Paylaşımlar', d: 'Gönderi, Reels ve story’leriniz – akışı doğrudan bir paylaşıma bağlayın.' },
        { t: 'Raporlar', d: 'Başlayan, link açılan, tamamlanan – gün ve akış bazında.' },
      ],
    },
    process: {
      eyebrow: 'Süreç',
      line1: 'Talepten',
      line2: 'yayına.',
      steps: [
        { t: 'Görüşme', d: 'Hedefi, kelimeleri ve hangi paylaşımların otomatik cevap vereceğini konuşuruz.', time: '1. gün' },
        { t: 'Erişim', d: 'Instagram hesabınızı „Instagram ile bağlan“ ile kendiniz bağlarsınız – şifrenizi görmeyiz.', time: '1. gün' },
        { t: 'İçerik', d: 'Metinleri, linkleri ve düğmeleri siz verirsiniz – ya da birlikte yazarız.', time: '2. gün' },
        { t: 'Kurulum', d: 'Akışları kurar, simülatörde ve test hesabıyla deneriz.', time: '2.–3. gün' },
        { t: 'Yayın', d: 'Açarız, birlikte kontrol ederiz, ekibiniz panele erişim alır.', time: '3. gün' },
      ],
      needTitle: 'Sizden ihtiyacımız olanlar',
      need: [
        { t: 'Instagram İşletme ya da İçerik Üretici hesabı', d: 'Instagram ayarlarından ücretsiz değiştirilir.' },
        { t: 'Facebook sayfası ve Meta Business Portfolio', d: 'Instagram hesabına bağlı, iki adımlı doğrulama açık. Komplett pakette bunu sizinle kurarız.' },
        { t: 'Tek tık „Instagram ile bağlan“', d: 'Resmî Meta girişi. Erişim şifreli saklanır.' },
        { t: 'Kelimeler & metinler', d: 'Hangi kelime neyi başlatsın? Hangi cevap, hangi link?' },
        { t: 'Ekibinizin e-posta adresleri', d: 'Panele kodla giriş – şifre yok.' },
      ],
      sendTitle: 'Bize nasıl iletirsiniz',
      send: 'Metinleri ve linkleri e-postayla ya da talep formuna not olarak. Erişim bilgilerini ve şifreleri asla e-postayla göndermeyin – bağlantıyı tek tıkla kendiniz yaparsınız.',
    },
    security: {
      eyebrow: 'Veri & Güvenlik',
      line1: 'Verileriniz',
      line2: 'Avrupa’da kalır.',
      items: [
        { t: 'Veritabanı Frankfurt’ta', d: 'Akışlar, sohbetler ve raporlar AB’deki kendi veritabanında durur.' },
        { t: 'Erişimler şifreli', d: 'Instagram anahtarları AES-256 ile şifrelenir, tarayıcı asla okuyamaz.' },
        { t: 'İmzalı mesajlar', d: 'Instagram’dan gelen her bildirim işlenmeden önce imzasıyla kontrol edilir.' },
        { t: 'Otomatik yenileme', d: 'Instagram erişimi her gün kontrol edilir ve zamanında yenilenir.' },
        { t: 'Veri silme', d: 'Kişiler verilerini istedikleri an sildirebilir – sayfası hazır.' },
        { t: 'Şifresiz giriş', d: 'Ekibiniz e-postayla gelen tek kullanımlık kodla girer.' },
      ],
      dbTitle: 'Ayrı bir veritabanı gerekir mi?',
      dbText: 'Evet – kurulumda sizin için açılır. Çoğu işletmeye ücretsiz katman yeter; çok yoğun sohbette bir üst katmanı konuşuruz.',
    },
    pricing: {
      eyebrow: 'Fiyat & Talep',
      line1: 'Net',
      line2: 'fiyatlar.',
      lede: 'Bir kez kurulur, sonra kendi çalışır. Ne kadarını bize bırakacağınızı siz seçersiniz – hazır hesaptan Meta’daki her işe kadar.',
      included: ['Kurulum ve ilk akışlar', 'Ekibiniz için panel erişimi', 'AB’de veritabanı', 'Tanıtım ve test', 'Aylık abonelik yok'],
      terms: [
        { t: 'Tek seferlik', d: 'Bir kez kurulur – sonra kendi kendine çalışır.' },
        { t: 'Yazılım için aylık ücret yok', d: 'Lisans ücreti yok – destek sadece isterseniz.' },
        { t: 'Sabit fiyat', d: 'Fiyatı baştan görürsünüz. Sürpriz yok.' },
        { t: 'Tanıtım dahil', d: 'Ekibinize her şeyi bir kez sakince gösteririz. Sürekli destek istenirse ek ücretle mümkündür.' },
      ],
      includedLabel: 'Dahil',
      hostingNote: 'Veritabanı ve barındırma: çoğu durumda ücretsiz.',
      currency: 'CHF',
      packsTitle: 'Paketler',
      choose: 'Bu paketi iste',
      recommended: 'Önerilen',
      packs: [
        {
          name: 'Start',
          price: '290',
          unit: 'tek sefer',
          for: 'Instagram profesyonel hesabınız, Facebook sayfanız ve Meta Business Portfolio’nuz hazır.',
          incl: ['Meta uygulaması ve webhook', 'Panel ve AB’de veritabanı', 'Akışlarınız', 'Tanıtım ve test'],
        },
        {
          name: 'Komplett',
          price: '490',
          unit: 'tek sefer',
          for: 'Hiçbir şeyle uğraşmak istemiyorsunuz – Meta’daki her işi de biz yaparız.',
          incl: ['Start’taki her şey', 'Meta’da işletme doğrulaması', 'Meta uygulama incelemesi', 'Giriş için e-posta göndericisi'],
        },
      ],
      careTitle: 'Destek – isteğe bağlı',
      care: [
        { name: 'Basis', price: '39', unit: 'aylık', d: 'E-postayla sorular (48 saatte cevap), ayda bir küçük değişiklik, Meta değişikliklerinde güncelleme.' },
        { name: 'Plus', price: '79', unit: 'aylık', d: 'Sınırsız küçük değişiklik, yeni akışlar, öncelik.' },
      ],
      hourly: 'Destek almadan: tek tek işler saati CHF 90.–',
      checkTitle: 'Gerekenler',
      checkHint: 'Hazır olanları işaretleyin – size hangi paketin uyduğunu söyleyelim.',
      readyAll: 'Her şey hazır – Start paketi yeter.',
      readySome: 'Henüz hepsi hazır değil – Komplett bunu sizin yerinize yapar.',
      checkGroups: [
        {
          t: 'Sizin hesaplarınız',
          own: true,
          items: [
            { t: 'Instagram profesyonel hesap', d: 'İşletme ya da İçerik Üretici – Instagram ayarlarından değiştirilir.' },
            { t: 'Facebook sayfası', d: 'Instagram hesabına bağlı.' },
            { t: 'İki adımlı doğrulama', d: 'Facebook hesabınızda açık – Meta bunu şart koşar.' },
            { t: 'Meta Business Portfolio', d: 'Sayfa ve Instagram hesabı içinde, siz yönetici.' },
            { t: 'Firma belgesi', d: 'Ticaret sicili çıktısı ya da UID, adres, telefon – Meta doğrulaması için.' },
          ],
        },
        {
          t: 'Teknik – Komplett pakette bizden',
          own: false,
          items: [
            { t: 'Meta geliştirici hesabı ve uygulama', d: '' },
            { t: 'Mesaj ve yorum izinleri', d: '' },
            { t: 'Meta uygulama incelemesi', d: 'Gizlilik ve silme sayfası, ekran videosu – günler ile haftalar sürer.' },
            { t: 'Webhook, AB’de veritabanı, barındırma', d: '' },
            { t: 'Giriş kodları için e-posta göndericisi', d: '' },
            { t: 'Erişimin otomatik yenilenmesi', d: '' },
          ],
        },
        {
          t: 'Sizin içerikleriniz',
          own: false,
          items: [
            { t: 'Kelimeler, cevaplar, linkler', d: 'Hangi kelime neyi başlatsın?' },
            { t: 'Ekibinizin e-posta adresleri', d: 'Panele giriş için.' },
          ],
        },
      ],
      form: {
        namePlaceholder: 'Adınız',
        emailPlaceholder: 'E-posta adresiniz',
        messagePlaceholder: 'Instagram hesabınız ve ne için kullandığınız …',
        successTitle: 'E-posta programı açıldı',
        successText: 'Talebiniz hazır – lütfen e-posta programında gönderin.',
        mailSubjectPrefix: 'InstaOto talebi:',
      },
    },
  },
};

export type InstaTexts = (typeof instaTexts)['de'];
