/**
 * ADO InstaOto - Instagram-Automatisierung (Produkt: D:\repos\instagramoto).
 * Neue Texte fuer die Website (nicht aus einem anderen Projekt kopiert). DE + TR.
 */
export const instaTexts = {
  de: {
    nav: {
      start: 'Übersicht',
      flow: 'So funktioniert’s',
      features: 'Funktionen',
      process: 'Ablauf',
      security: 'Daten & Sicherheit',
      pricing: 'Preise & Anfrage',
    },
    group: { title: 'ADO InstaOto · Automation', short: 'Insta' },
    start: {
      eyebrow: 'Instagram-Automatisierung',
      line1: 'Jeder Kommentar',
      line2: 'bekommt eine Antwort.',
      lede: 'Schreibt jemand unter Ihren Beitrag, in eine Story-Antwort oder per DM ein Stichwort, startet automatisch ein Gespräch: mit Knöpfen, Follow-Prüfung, Link und Übergabe an Ihr Team – rund um die Uhr, ohne Monatsabo.',
      stats: [
        { v: '6 s', l: 'bis zur ersten Antwort' },
        { v: '24/7', l: 'automatisch erreichbar' },
        { v: '0', l: 'Monatsabo' },
        { v: '3', l: 'Kanäle: Kommentar, DM, Story' },
      ],
      video: 'Film ansehen',
      cta: 'So funktioniert’s',
    },
    flow: {
      eyebrow: 'Live ausprobieren',
      line1: 'Schreiben Sie',
      line2: '„Detail“.',
      hint: 'Tippen Sie ein Stichwort wie die Kundschaft – die Antwort kommt sofort.',
      placeholder: 'Kommentar schreiben …',
      send: 'Senden',
      user: 'lena.design',
      steps: ['Stichwort erkannt', 'Antwort mit Knöpfen', 'Follow-Prüfung', 'Link gesendet'],
      stepsHint: 'Schritt anklicken – das Telefon spielt ihn vor',
      bot: {
        hello: 'Hallo 👋 Möchtest du unsere Leistungen und Pakete sehen?',
        buttons: ['Ja, zeigen', 'Nein', 'Weiss nicht'],
        follow: 'Folgst du uns schon? Dann schicke ich dir gleich den Link.',
        followBtn: 'Ich folge',
        link: 'Hier ist alles im Überblick:',
        no: 'Kein Problem – schreib einfach „Detail“, wenn du es dir anders überlegst.',
        human: 'Ich gebe dich an unser Team weiter. Wir melden uns persönlich.',
        unknown: 'Unbekanntes Stichwort. Versuchen Sie „Detail“, „Preis“ oder „Link“.',
      },
      keywords: ['Detail', 'Preis', 'Link'],
    },
    features: {
      eyebrow: 'Das Panel',
      line1: 'Alles in',
      line2: 'einer Oberfläche.',
      items: [
        { t: 'Abläufe', d: 'Stichwörter, Kanäle und Beiträge festlegen – ein- und ausschalten mit einem Klick.' },
        { t: 'Editor', d: 'Schritte mit Knöpfen, Verzweigungen, Follow-Prüfung und Link. Instagram-Regeln werden live geprüft.' },
        { t: 'Simulator', d: 'Jeden Ablauf vorab am Telefon-Vorschau testen – mit der echten Logik.' },
        { t: 'Posteingang', d: 'Alle Gespräche pro Person; übergebene Anfragen beantwortet Ihr Team direkt.' },
        { t: 'Beiträge', d: 'Ihre Posts, Reels und Stories – einen Ablauf direkt an einen Beitrag hängen.' },
        { t: 'Auswertung', d: 'Gestartet, Link geöffnet, abgeschlossen – pro Tag und pro Ablauf.' },
      ],
    },
    process: {
      eyebrow: 'Ablauf',
      line1: 'Von der Anfrage',
      line2: 'bis live.',
      steps: [
        { t: 'Gespräch', d: 'Wir klären Ziel, Stichwörter und welche Beiträge automatisch antworten sollen.', time: 'Tag 1' },
        { t: 'Zugänge', d: 'Sie verbinden Ihr Instagram-Konto selbst über „Mit Instagram verbinden“ – wir sehen kein Passwort.', time: 'Tag 1' },
        { t: 'Inhalte', d: 'Sie liefern Texte, Links und Knöpfe – oder wir schreiben sie mit Ihnen.', time: 'Tag 2' },
        { t: 'Einrichtung', d: 'Wir bauen die Abläufe, testen sie im Simulator und mit einem Testkonto.', time: 'Tag 2–3' },
        { t: 'Live', d: 'Freischalten, gemeinsam prüfen, Ihr Team bekommt den Zugang zum Panel.', time: 'Tag 3' },
      ],
      needTitle: 'Was wir von Ihnen brauchen',
      need: [
        { t: 'Instagram Business- oder Creator-Konto', d: 'Kostenlos in den Instagram-Einstellungen umstellbar.' },
        { t: 'Ein Klick „Mit Instagram verbinden“', d: 'Offizielle Meta-Anmeldung. Der Zugang wird verschlüsselt gespeichert.' },
        { t: 'Stichwörter & Texte', d: 'Welche Wörter lösen was aus? Welche Antwort, welcher Link?' },
        { t: 'E-Mail-Adressen Ihres Teams', d: 'Anmeldung am Panel per Code – ohne Passwort.' },
      ],
      sendTitle: 'So schicken Sie uns alles',
      send: 'Texte und Links per E-Mail oder als Notiz im Anfrageformular. Zugänge und Passwörter schicken Sie nie per E-Mail – die Verbindung machen Sie selbst mit einem Klick.',
    },
    security: {
      eyebrow: 'Daten & Sicherheit',
      line1: 'Ihre Daten',
      line2: 'bleiben in Europa.',
      items: [
        { t: 'Datenbank in Frankfurt', d: 'Abläufe, Gespräche und Auswertungen liegen in einer eigenen Datenbank in der EU.' },
        { t: 'Zugänge verschlüsselt', d: 'Instagram-Schlüssel werden mit AES-256 verschlüsselt und sind für den Browser nie lesbar.' },
        { t: 'Signierte Nachrichten', d: 'Jede Meldung von Instagram wird über ihre Signatur geprüft, bevor sie verarbeitet wird.' },
        { t: 'Automatische Verlängerung', d: 'Der Instagram-Zugang wird täglich geprüft und rechtzeitig erneuert.' },
        { t: 'Datenlöschung', d: 'Personen können ihre Daten jederzeit löschen lassen – die Seite dafür ist eingerichtet.' },
        { t: 'Anmeldung ohne Passwort', d: 'Ihr Team meldet sich mit einem Einmal-Code per E-Mail an.' },
      ],
      dbTitle: 'Braucht es eine eigene Datenbank?',
      dbText: 'Ja – sie wird bei der Einrichtung für Sie angelegt. Für die meisten Betriebe reicht die kostenlose Stufe; bei sehr vielen Gesprächen sprechen wir über die nächste Stufe.',
    },
    pricing: {
      eyebrow: 'Preise & Anfrage',
      line1: 'Preis',
      line2: 'auf Anfrage.',
      lede: 'Jede Einrichtung ist auf Ihren Betrieb zugeschnitten. Erzählen Sie uns kurz, wofür Sie Instagram nutzen – Sie erhalten ein klares Angebot ohne Monatsabo.',
      included: ['Einrichtung und erste Abläufe', 'Panel-Zugang für Ihr Team', 'Datenbank in der EU', 'Einweisung und Test', 'Kein Monatsabo'],
      form: {
        namePlaceholder: 'Ihr Name',
        emailPlaceholder: 'Ihre E-Mail-Adresse',
        messagePlaceholder: 'Ihr Instagram-Konto und wofür Sie es nutzen …',
        successTitle: 'Mailprogramm geöffnet',
        successText: 'Ihre Anfrage ist vorbereitet – bitte im Mailprogramm noch abschicken.',
        mailSubjectPrefix: 'InstaOto-Anfrage von',
      },
    },
  },
  tr: {
    nav: {
      start: 'Genel Bakış',
      flow: 'Nasıl çalışır',
      features: 'Özellikler',
      process: 'Süreç',
      security: 'Veri & Güvenlik',
      pricing: 'Fiyat & Talep',
    },
    group: { title: 'ADO InstaOto · Otomasyon', short: 'Insta' },
    start: {
      eyebrow: 'Instagram otomasyonu',
      line1: 'Her yorum',
      line2: 'bir cevap alır.',
      lede: 'Biri gönderinizin altına, story cevabına ya da DM’e bir kelime yazınca otomatik bir sohbet başlar: düğmeler, takip kontrolü, link ve ekibinize devretme – 7/24, aylık abonelik olmadan.',
      stats: [
        { v: '6 sn', l: 'ilk cevaba kadar' },
        { v: '7/24', l: 'otomatik ulaşılabilir' },
        { v: '0', l: 'aylık abonelik' },
        { v: '3', l: 'kanal: yorum, DM, story' },
      ],
      video: 'Filmi izle',
      cta: 'Nasıl çalışır',
    },
    flow: {
      eyebrow: 'Canlı deneyin',
      line1: 'Yazın:',
      line2: '„Detay“.',
      hint: 'Müşteri gibi bir kelime yazın – cevap hemen gelir.',
      placeholder: 'Yorum yaz …',
      send: 'Gönder',
      user: 'lena.design',
      steps: ['Kelime tanındı', 'Düğmeli cevap', 'Takip kontrolü', 'Link gönderildi'],
      stepsHint: 'Bir adıma tıklayın – telefon onu oynatır',
      bot: {
        hello: 'Merhaba 👋 Hizmetlerimizi ve paketlerimizi görmek ister misin?',
        buttons: ['Evet, göster', 'Hayır', 'Bilmiyorum'],
        follow: 'Bizi takip ediyor musun? O zaman linki hemen gönderiyorum.',
        followBtn: 'Takip ediyorum',
        link: 'Hepsi burada:',
        no: 'Sorun değil – fikrin değişirse „Detay“ yazman yeterli.',
        human: 'Seni ekibimize aktarıyorum. Kişisel olarak dönüş yapacağız.',
        unknown: 'Bilinmeyen kelime. „Detay“, „Fiyat“ ya da „Link“ deneyin.',
      },
      keywords: ['Detay', 'Fiyat', 'Link'],
    },
    features: {
      eyebrow: 'Panel',
      line1: 'Her şey',
      line2: 'tek ekranda.',
      items: [
        { t: 'Akışlar', d: 'Kelimeleri, kanalları ve gönderileri belirleyin – tek tıkla açıp kapatın.' },
        { t: 'Düzenleyici', d: 'Düğmeli adımlar, dallanma, takip kontrolü ve link. Instagram kuralları anında kontrol edilir.' },
        { t: 'Simülatör', d: 'Her akışı önceden telefon önizlemesinde gerçek motorla deneyin.' },
        { t: 'Gelen kutusu', d: 'Kişi bazında tüm sohbetler; devredilen talepleri ekibiniz doğrudan cevaplar.' },
        { t: 'Paylaşımlar', d: 'Gönderi, Reels ve story’leriniz – akışı doğrudan bir paylaşıma bağlayın.' },
        { t: 'Raporlar', d: 'Başlayan, link açılan, tamamlanan – gün ve akış bazında.' },
      ],
    },
    process: {
      eyebrow: 'Süreç',
      line1: 'Talepten',
      line2: 'yayına.',
      steps: [
        { t: 'Görüşme', d: 'Hedefi, kelimeleri ve hangi paylaşımların otomatik cevap vereceğini konuşuruz.', time: '1. gün' },
        { t: 'Erişim', d: 'Instagram hesabınızı „Instagram ile bağlan“ ile kendiniz bağlarsınız – şifrenizi görmeyiz.', time: '1. gün' },
        { t: 'İçerik', d: 'Metinleri, linkleri ve düğmeleri siz verirsiniz – ya da birlikte yazarız.', time: '2. gün' },
        { t: 'Kurulum', d: 'Akışları kurar, simülatörde ve test hesabıyla deneriz.', time: '2.–3. gün' },
        { t: 'Yayın', d: 'Açarız, birlikte kontrol ederiz, ekibiniz panele erişim alır.', time: '3. gün' },
      ],
      needTitle: 'Sizden ihtiyacımız olanlar',
      need: [
        { t: 'Instagram İşletme ya da İçerik Üretici hesabı', d: 'Instagram ayarlarından ücretsiz değiştirilir.' },
        { t: 'Tek tık „Instagram ile bağlan“', d: 'Resmî Meta girişi. Erişim şifreli saklanır.' },
        { t: 'Kelimeler & metinler', d: 'Hangi kelime neyi başlatsın? Hangi cevap, hangi link?' },
        { t: 'Ekibinizin e-posta adresleri', d: 'Panele kodla giriş – şifre yok.' },
      ],
      sendTitle: 'Bize nasıl iletirsiniz',
      send: 'Metinleri ve linkleri e-postayla ya da talep formuna not olarak. Erişim bilgilerini ve şifreleri asla e-postayla göndermeyin – bağlantıyı tek tıkla kendiniz yaparsınız.',
    },
    security: {
      eyebrow: 'Veri & Güvenlik',
      line1: 'Verileriniz',
      line2: 'Avrupa’da kalır.',
      items: [
        { t: 'Veritabanı Frankfurt’ta', d: 'Akışlar, sohbetler ve raporlar AB’deki kendi veritabanında durur.' },
        { t: 'Erişimler şifreli', d: 'Instagram anahtarları AES-256 ile şifrelenir, tarayıcı asla okuyamaz.' },
        { t: 'İmzalı mesajlar', d: 'Instagram’dan gelen her bildirim işlenmeden önce imzasıyla kontrol edilir.' },
        { t: 'Otomatik yenileme', d: 'Instagram erişimi her gün kontrol edilir ve zamanında yenilenir.' },
        { t: 'Veri silme', d: 'Kişiler verilerini istedikleri an sildirebilir – sayfası hazır.' },
        { t: 'Şifresiz giriş', d: 'Ekibiniz e-postayla gelen tek kullanımlık kodla girer.' },
      ],
      dbTitle: 'Ayrı bir veritabanı gerekir mi?',
      dbText: 'Evet – kurulumda sizin için açılır. Çoğu işletmeye ücretsiz katman yeter; çok yoğun sohbette bir üst katmanı konuşuruz.',
    },
    pricing: {
      eyebrow: 'Fiyat & Talep',
      line1: 'Fiyat',
      line2: 'talep üzerine.',
      lede: 'Her kurulum işletmenize göre yapılır. Instagram’ı ne için kullandığınızı kısaca yazın – aylık abonelik olmadan net bir teklif alırsınız.',
      included: ['Kurulum ve ilk akışlar', 'Ekibiniz için panel erişimi', 'AB’de veritabanı', 'Tanıtım ve test', 'Aylık abonelik yok'],
      form: {
        namePlaceholder: 'Adınız',
        emailPlaceholder: 'E-posta adresiniz',
        messagePlaceholder: 'Instagram hesabınız ve ne için kullandığınız …',
        successTitle: 'E-posta programı açıldı',
        successText: 'Talebiniz hazır – lütfen e-posta programında gönderin.',
        mailSubjectPrefix: 'InstaOto talebi:',
      },
    },
  },
};

export type InstaTexts = (typeof instaTexts)['de'];
